export const carCompany = [
  {company: "Tesla"},
  {company: "Mazda"},
  {company: "BMW"},
  {company: "Subaru"},
  {company: "Porsche"},
  {company: "Honda"},
  {company: "Lexus"},
  {company: "Toyota"},
  {company: "Chrysler"},
  {company: "Buick"},
  {company: "Hyundai"},
  {company: "Audi"},
  {company: "Dodge"},
  {company: "Nissan"},
  {company: "Genesis"},
  {company: "Mini"},
  {company: "Volkswagen"},
  {company: "Kia"},
  {company: "Volvo"},
  {company: "Mercedes-Benz"},
  {company: "Cadillac"},
  {company: "Acura"},
  {company: "Jeep"},
  {company: "Ford"},
  {company: "Alfa Romeo"},
  {company: "Jaguar"},
  {company: "Chevrolet"},
  {company: "Bentley"},
  {company: "Mitsubishi"},
  {company: "Land Rover"}
];

export const carModel = [
  {model: "Model 3"},
  {model: "Getz"},
  {model: "M2"},
  {model: "Continental"},
  {model: "Escort"},
  {model: "HR-V"},
  {model: "Tucson"},
  {model: "Pilot"},
  {model: "Amg"},
  {model: "Focus"},
  {model: "Camaro"},
  {model: "Corolla"},
  {model: "Gtr"},
  {model: "4Runner"},
  {model: "Escape"},
  {model: "Outback"},
  {model: "Forester"},
  {model: "CX-5"},
  {model: "Equinox"},
  {model: "Accord"},
  {model: "Wrangler"},
  {model: "Explorer"},
  {model: "Sierra"},
  {model: "Tacoma"},
  {model: "Cherokee"},
  {model: "Civic"},
  {model: "Highlander"},
  {model: "Rogue"},
  {model: "Camry"},
  {model: "Silverado"}
];